[project]
name = "transpiler"
version = "0.1.0"
description = "Python to JavaScript transpiler for Parable"
requires-python = ">=3.14"

[project.scripts]
transpiler = "transpiler:main"

[build-system]
requires = ["uv_build>=0.9.26"]
build-backend = "uv_build"
